sudo: false
language: python
cache: false
services:
  - docker
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=check
    - python: '3.6'
      env:
        - TOXENV=docs
    - env:
        - TOXENV=py36-cover
      python: '3.6'
    - env:
        - TOXENV=py36-nocov
      python: '3.6'
    - env:
        - TOXENV=py37-cover
      python: '3.7'
    - env:
        - TOXENV=py37-nocov
      python: '3.7'
    - env:
        - TOXENV=py38-cover
      python: '3.8'
    - env:
        - TOXENV=py38-nocov
      python: '3.8'
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
  - docker run -d --rm -p 15672:15672 -p 5672:5672 --name rabbitmq rabbitmq:3-management
install:
  - python -mpip install --progress-bar=off tox -rci/requirements.txt
  - virtualenv --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
